exclude: ".yarn/|yarn.lock|\\.min\\.(css|js)$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.21.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.4"
    hooks:
      - id: ruff
        args: [--unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 2.2.3
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.19
    hooks:
      - id: validate-pyproject
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier@3.3.3 --no-semi --write
        language: system
        types_or: [css, scss]
        require_serial: true
      - id: eslint
        name: eslint
        entry: yarn eslint
        language: system
        types_or: [javascript]
        require_serial: true
        verbose: true
