exclude: ".yarn/|yarn.lock"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.270"
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        args: [--list-different, --no-semi, "--trailing-comma=es5"]
        exclude: "^conf/|.*\\.html$"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.41.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - "@babel/core"
          - "@babel/eslint-parser"
          - "@babel/preset-env"
