[tox]
envlist =
    py{310,311,312}-dj42
    py{312,313}-dj{52,main}
    py{314}-dj{52,60,main}
    docs
    slowtests

[testenv]
usedevelop = true
extras = all,tests
commands =
    pytest --cov=feincms3 --cov-report=term-missing {posargs:tests/testapp}
deps =
    pytest
    pytest-cov
    pytest-django
    dj42: Django>=4.2,<5.0
    # 4.13 and better require Django 5.2 or better
    dj42: pytest-django<4.13
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
    djmain: https://github.com/django/django/archive/main.tar.gz

[testenv:docs]
deps =
    Sphinx
    furo
    Django
    django-ckeditor
    django-content-editor
    django-tree-queries>=0.4.1
    django-imagefield
    html-sanitizer
    requests
changedir = docs
commands = make html
skip_install = true
allowlist_externals = make

[testenv:slowtests]
usedevelop = true
extras = all,tests
setenv =
    SLOWTESTS=1
commands =
    pytest --cov=feincms3 --cov-report=term-missing tests/testapp
deps =
    django-slowtests
